/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estructuras.Nodo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class TablaExpedientes extends javax.swing.JFrame {

    /**
     * Creates new form TablaExpedientes
     * @param NombreEstructura
     */
    public TablaExpedientes(String NombreEstructura) {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID", "DNI", "Nombres", "Apellidos", "Email", "Phone", "Tipo", "Asunto", "Dependencia", "Prioridad","Estado", "Fecha Inicio" , "Fecha Termino","Actas"}, 0
            );
        TablaExpediente.setModel(model);
        /*Diseño*/
        TablaExpediente.setGridColor(new java.awt.Color(200, 200, 200));
        TablaExpediente.setShowGrid(true);
        javax.swing.table.JTableHeader header = TablaExpediente.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                c.setBackground(new java.awt.Color(255, 153, 51));
                c.setForeground(java.awt.Color.BLACK);
                setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
                return c;
            }
        });
        TablaExpediente.getTableHeader().setReorderingAllowed(false);
        TablaExpediente.setRowHeight(24);
        TablaExpediente.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        TablaExpediente.setForeground(java.awt.Color.BLACK);
        TablaExpediente.setBackground(java.awt.Color.WHITE);

        header.setReorderingAllowed(false);

        javax.swing.table.TableCellRenderer zebraRenderer = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    c.setBackground(row % 2 == 0 ? java.awt.Color.WHITE : new java.awt.Color(255, 153, 51));
                    c.setForeground(java.awt.Color.BLACK);
                } else {
                    c.setBackground(new java.awt.Color(184, 207, 229));
                    c.setForeground(java.awt.Color.BLACK);
                }
                return c;
            }
        };

        for (int i = 0; i < TablaExpediente.getColumnCount(); i++) {
            TablaExpediente.getColumnModel().getColumn(i).setCellRenderer(zebraRenderer);
        }
        
        Nodo iterador = null;
        if ("ColaSP".equals(NombreEstructura)) {
            iterador = Main.ColaSinProcesar.head;
        } else if ("ColaEP".equals(NombreEstructura)) {
            iterador = Main.ColaEnProceso.head;
        } else if ("ColaMaster".equals(NombreEstructura)) {
            iterador = Main.ColaMaster.head;
        } else if ("PilaF".equals(NombreEstructura)) {
            iterador = Main.PilaFinalizados.head;
        }
        while (iterador != null){
            ConstruirTabla(iterador);
            iterador = iterador.siguiente;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExpediente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaExpediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaExpediente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 260));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setText("Regresar");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Main Main = new Main();
        Main.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    public void ConstruirTabla(Nodo node){
        DefaultTableModel model = (DefaultTableModel) TablaExpediente.getModel();
            model.addRow(new Object[]{
                node.getExp().getId(),
                node.getExp().getDocumento().getDNI(),
                node.getExp().getDocumento().getNombres(),
                node.getExp().getDocumento().getApellidos(),
                node.getExp().getDocumento().getEmail(),
                node.getExp().getDocumento().getPhone(),
                node.getExp().getTipo(),
                node.getExp().getAsunto(),
                node.getExp().getDependencia(),
                node.getExp().getPrioridad(),
                node.getExp().getEstado(),
                node.getExp().getFechaingreso(),
                node.getExp().getFechatermino(),
                node.getExp().getActa(),
            });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable TablaExpediente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
